
export type SNTokenType = "Color" | "Typography" | "Radius" | "Font" | "Measure" | "Shadow" | "Border" | "Gradient" | "Text"
export type SNTokenPropertyType = "Number" | "Boolean" | "String" | "Generic"
export type SNSourceType = "Supernova" | "Figma"
export type SNTextCase = "Original" | "Upper" | "Lower" | "Camel"
export type SNTextDecoration = "None" | "Underline" | "Strikethrough"
export type SNUnit = "Pixels" | "Points" | "Percent" | "Ems"
export type SNBorderPosition = "Inside" | "Center" | "Outside"
export type SNGradientType = "Linear" | "Radial" | "Angular"
export type SNDocumentationItemType = "Page" | "Group"
export type SNDocumentationPageBlockType =
    | "Text"
    | "Heading"
    | "Code"
    | "UnorderedList"
    | "OrderedList"
    | "Quote"
    | "Callout"
    | "Divider"
    | "Image"
    | "Link"
    | "Token"
    | "TokenList"
    | "TokenGroup"
    | "Shortcuts"
    | "FigmaEmbed"
    | "YoutubeEmbed"
    | "Embed"
    | "FigmaFrames"

export type SNRichTextSpanAttributeType = "Bold" | "Italic" | "Link" | "Strikethrough" | "Code"
export type SNCalloutType = "Info" | "Success" | "Warning" | "Error"
export type SNHeadingType = "1" | "2" | "3"
export type SNContentAlignment = "Left" | "Center" | "Stretch"
export type SNHeaderAlignment = "Default" | "Center"
export type SNFrameAlignment = "FrameHeight" | "Center"
export type SNFrameLayout = "C8" | "C7" | "C5" | "C4" | "C3" | "C2" | "C1" | "C1_75"
export type SNShortcutType = "Internal" | "External"
export type SNShadowType = "Inner" | "Outer"
export type SNDocumentationPageBlockCodeLiveSandboxType = "React"